### ISSUE TITLE
macOS osx_url_schemes not working

### ISSUE THREAD

**Issue by ShayBox** [burtonageo/cargo-bundle#125]
```toml
[package.metadata.bundle]
identifier = "com.shaybox.launcher-curseforge"
linux_mime_types = ["x-scheme-handler/curseforge"]
linux_exec_args = "%u"
osx_url_schemes = ["curseforge"]
```
I added this to my `Cargo.toml` but it doesn't populate any `CFBundleURLTypes` in the `Info.plist` file  

EDIT: The linux options worked fine, only this mac one doesn't
