### ISSUE TITLE
IOS bundle bug in binary mode

### ISSUE THREAD

**Issue by SmnTin** [burtonageo/cargo-bundle#126]
If we have the following `Cargo.toml`:
```toml
[package]
name = "example"
version = "0.1.0"
description = "An example application."

[package.metadata.bundle.bin.app]
identifier = "com.example.myapp"

[[bin]]
name = "app"
```

And we bundle it with:
```console
$ cargo bundle --target aarch64-apple-ios-sym --bin app
```

Then the resulted `.app` will be invalid. In particular, it will have the following structure:
```
example.app:
├── example
└── Info.plist
```

The contents of `Info.plist` will be:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleIdentifier</key>
  <string>com.example.myapp</string>
  <key>CFBundleDisplayName</key>
  <string>example</string>
  <key>CFBundleName</key>
  <string>example</string>
  <key>CFBundleExecutable</key>
  <string>app</string>
  <key>CFBundleVersion</key>
  <string>0.1.0</string>
  <key>CFBundleShortVersionString</key>
  <string>0.1.0</string>
  <key>CFBundleDevelopmentRegion</key>
  <string>en_US</string>
  <key>UILaunchStoryboardName</key>
  <string></string>
  <key>LSRequiresIPhoneOS</key>
  <true/>
</dict>
</plist>
```

As you can see, the binary name in the bundle is the same as the package name, i.e. `example`, but in `Info.plist` it is referred as `app` (`CFBundleExecutable` field).

As a result, such app is not installable on the simulator.
