### ISSUE TITLE
Support for Bundling Multiple Binaries in One Installer

### ISSUE THREAD

**Issue by joelonsql** [burtonageo/cargo-bundle#163]
I'd like to propose an enhancement to bundle multiple binary crates into a single installer/package. This is beneficial for projects comprising several binaries (e.g., main app, helper tools, daemons) that should be distributed together.

Proposal:

Extend `[package.metadata.bundle]` to accept multiple binary targets.
Allow separate configurations for each binary.

Example:
```toml
[package.metadata.bundle]
bins = ["app1", "app2"]

[package.metadata.bundle.app1]
# ... settings ...

[package.metadata.bundle.app2]
# ... settings ...
```

This would make distribution of multi-binary Rust projects simpler and more user-friendly.

Thank you for considering this enhancement!
