### ISSUE TITLE
Menu Item name is not shown on macOS

### ISSUE THREAD

**Issue by hacknus** [burtonageo/cargo-bundle#171]
On macOS 14.1 (Apple Silicon) the menu item no longer shows the name given in
```toml
[package.metadata.bundle]
name = "Application Name"
```
but displays the system default `NSMenuItem`.
