### ISSUE TITLE
Suggestion: use the cargo metadata table

### ISSUE THREAD

**Issue by jansegre** [burtonageo/cargo-bundle#5]
I haven't checked when this was introduced, but currently it is possible to use  `Cargo.toml` for [storing external metadata info](http://doc.crates.io/manifest.html#the-metadata-table-optional).

This would work by putting the following on `Cargo.toml`

``` toml
[package.metadata.bundle]
name = "ExampleApplication"
identifier = "com.doe.exampleapplication"
icon = ["32x32.png", "128x128.png", "128x128@2x.png"]
version = "1.0.0"
resources = ["assets", "configuration", "secrets/public_key.txt"]
copyright = "Copyright (c) Jane Doe 2016. All rights reserved."
```

When maintaining packages I always prefer to keep things close, and having them on a single file seems like a good idea.

What do you think?
