### ISSUE TITLE
Multiple separate packages

### ISSUE THREAD

**Issue by rubdos** [burtonageo/cargo-bundle#51]
Hi! Just bounced in here, thanks for the application. Currently testing it out!

I wondered whether it would be difficult to have a project split up in different packages; for example, I have three executables in my `src/bin`, and most of the time, executable A doesn't make sense to be installed, and vice versa.

**Comment by mdsteele** [comment]
Hmm, good question.

Right now, `cargo-bundle` will only package your crate's main executable, and in general will ignore `src/bin` and the `[[bin]]` section of your `Cargo.toml`.  It sounds like we should have `cargo-bundle` support the `--bin` (and `--example`) flags that `cargo build` and `cargo run` have, to allow you to selectively package those other apps as well.

To support this, we'd need a way to specify bundle metadata for each bin/example.  I just checked, and it doesn't look like `Cargo.toml` supports a freeform `metadata` table in e.g. the `[[example]]` section; only in the `[package]` section.  So maybe we could do something like this:

```toml
[package]
# other fields...

[package.metadata.bundle.bin.foo]
icon = ["icons/foo32x32.png"]
# other fields...

[package.metadata.bundle.bin.bar]
icon = ["icons/bar32x32.png"]
# other fields...

[package.metadata.bundle.example.baz]
icon = ["icons/baz32x32.png"]
# other fields...

[[bin]]
name = "foo"
path = "src/bin/foo.rs"
# other fields...

[[bin]]
name = "bar"
path = "src/bin/bar.rs"
# other fields...

[[example]]
name = "baz"
path = "examples/baz.rs"
# other fields...
```
