### ISSUE TITLE
Support zip and tar.gz bundles

### ISSUE THREAD

**Issue by achary** [burtonageo/cargo-bundle#72]
I suggest extending `cargo-bundle` with generating also ZIP and tar.gz acrhive bundles.
For many applications, espectially portable (like many of rust binaries are) it's 
quite convenient way to deploy the binaries over installers
(which may require user to have root/admin permissions).

The `Cargo.toml` configuration section could be extended with arrays of archive
type to generate on a specific platform:

```toml
[package.metadata.bundle]
osx_archives=["tar.gz"]
linux_archives=["tar.gz", "zip"]
windows_archives=["zip"]
```

For a package named `foo` version 0.1.0 on 64-bit Linux platform the output file could be:

```
foo_0.1.0_amd64.tar.gz
```

and could be generated aside other bundles (DEB, MSI etc).

The internall structure of the archive could follow the same structure that
OS specific bundles have at the moment, e.g. for Linux, same as  
DEB packages have with `bin`, `lib`, `share`) directories etc.
